language: node_js
node_js:
- '4.3'
env:
  - TEST_DIR=events
  - TEST_DIR=api
script: cd $TEST_DIR && npm install && npm test
cache:
  directories:
    - node_modules
    - events/node_modules
    - api/node_modules
