language: node_js
node_js:
- '4.3'
env:
  - TEST_DIR=events CXX=g++-4.8
  - TEST_DIR=api
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: cd $TEST_DIR && npm install && npm test
cache:
  directories:
    - node_modules
    - events/node_modules
    - api/node_modules
